config/routes.rb
Rails.application.routes.draw do


  root 'home#homepage'

  get "/search" => "users#search"

  get "/sign_in" => "sessions#new"
  post "/sign_in" => "sessions#create"
  get "/sign_up" => "users#new"
  post "/sign_up" => "users#create"
  get "/users/sign_out" => "sessions#destroy"


  resources :users
  resources :posts do
    resources :comments, shallow: true, only:[:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	validates_presence_of :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
	validates_uniqueness_of :username
	validates_presence_of :username, :password

    has_attached_file :avatar, 
    :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png" 
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	if session[:user_id]
  	  User.find(session[:user_id])
  	else
  	  nil
  	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @user = session[:user_id]
  	@comment = Comment.create(user_id: session[:user_id], post_id: params[:post_id], body: params[:comment][:body])
  	# @comment.user_id = session[:user_id]
  	# @comment.post_id = params[:id]
  	# if @comment.save
  	# 	flash[:notice] = "Comment posted"
  	# else
  	# 	flash[:alert] = "Comment not saved"
  	# end
    redirect_to :back, notice: "Comment posted."
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    id = session[:user_id]
    render :new, notice: "Comment deleted."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def homepage
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
  	@user = current_user
    @post = Post.new
  end

  def create
    body = params[:post][:body]
    id = session[:user_id]
    @post = Post.create(body: body, user_id: id)
    redirect_to user_path(id)
  end

  def edit
  end

  def update
    @user = @post.user
    @post.update(body: params[:post][:body])
    redirect_to user_path(@user), notice: "Sucessfully updated post."
  end

  def show
    @comment = Comment.new
    redirect_to user_path(@user)
  end

  def destroy
    @post.destroy
    id = session[:user_id]
    redirect_to user_path(id), notice: "Post successfully deleted."
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	@user = User.where(username: params[:username]).first
  	if @user && @user.password == params[:password]
  	    session[:user_id] = @user.id
  	    flash[:notice] = "You have logged in successfully"
        redirect_to user_path(@user)
  	else
  	  flash[:alert] = "Your information was incorrect."
      redirect_to sign_in_path
  	end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have signed out"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:notice] = "Welcome grasshopper! Now you can sign in."
  	else 
  		flash[:alert] = "There was a problem creating your account. Try again!"
  	end
  	redirect_to sign_in_path
  end
  
  def show
    @posts = @user.posts
    @comments = @user.comments
  end
  
  def edit
  end

  def update
    if @user.update(user_params)
    redirect_to user_path(@user), notice: "Sucessfully updated profile."
    else
    redirect_to edit_user_path(@user), alert: "There was an issue"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "User successfully deleted."
  end

  def search
    search_term = params[:query]
    search_results = User.where(username: search_term)
    if (search_results.length == 0)
      redirect_to users_path, alert: "No results found"
    elsif (search_results.length == 1)
      redirect_to user_path search_results.first
    else #multiple matches
      @users = search_results
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/homepage.html.erb
<body class="bg-home">
  <div class="container">
    <div class="welcome-wrapper">
	  <div class="title"><em>blabber.</em></div>
	  <div class="subtitle">Not just another blogging site. <strong>OK, it is.</strong> But we have this uber hip background photo, so come get your blab on!</div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>blabber</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="/stylesheets/style.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav id="nav">
  <div class="logo"><a href="/">blabber</a></div>
  <ul>
    <li><%= link_to "Community", users_path %></li>
    <% unless session[:user_id] %>
	  <li><%= link_to "Log In", sign_in_path %></li>
	  <li><%= link_to "Sign Up", sign_up_path %></li>
    <% end %>
    <% if session[:user_id] %>
    <li><%= link_to "My Feed", user_path(session[:user_id]) %></li>
    <li><%= link_to "New Post", new_post_path %></li>
    <li><%= link_to 'Edit Profile', edit_user_path(session[:user_id]) %></li>
    <li><%= link_to "Sign Out", users_sign_out_path %></li>
    <% end %> 
  </ul>
</nav>

  <% if flash[:notice] %>
    <div class="notice"><%=flash[:notice] %></div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert"><%=flash[:alert] %></div>
  <% end %>

<%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.text_area :body, :id =>"post-bx" %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<body class="bg-other">
  <div class="feed-wrapper">
    <div class="newpost-wrapper">
      <h3>Edit blab:</h3>
        <div class="post">
          <%= render 'form' %>
        </div>
    </div>
  </div>
  <%= link_to 'Back', :back %>
</body>

app/views/posts/index.html.erb
<% @post.each do |post| %>

<p>
  <%= post.body %>
</p>

<% if post.user %>
  Written by:
  <%= post.user.username %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<body class="bg-other">
  <div class="feed-wrapper">
    <div class="newpost-wrapper">
      <h3>Write a new blab:</h3>
        <div class="post">
          <%= render 'form' %>
        </div>
    </div>
  </div>
  <%= link_to "Back", :back, :class => "utility-links" %>
</body>

app/views/posts/show.html.erb
<% @posts.each do |post| %>

<p>
  <%= post.body %>
</p>

<% if post.user %>
  Written by:
    <%= post.user.username %>

<% end %>

<!-- <br><br>

<% @post.comment.each do |comment| %>
  <%= comment.body %>
  Comment by:
  <%= comment.user.username %>
<% end %>

<br><br> -->

<%= form_for Post.new do |t| %>
  <%= t.label :body %>
  <%= t.text_area :body %>
  <%= t.hidden_field :post_id, value: @post.id %>
  <%= t.submit %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, :url => user_path, :html => { :multipart => true } do |f| %>

  <div class="f-label"><%=f.label :username, class:"f-label" %></div>
  <div class="f-field"><%=f.text_field :username %></div>
  <div class="f-label"><%=f.label :password %></div>
  <div class="f-field"><%=f.password_field :password %></div>
  <div class="f-label"><%=f.label :profile_image %></div>
  <div class="f-field"><%= f.file_field :avatar %></div>
  <div class="create-user"><%=f.submit%></div>
<% end %>

app/views/users/edit.html.erb
<body class="bg-other">
<% if session[:user_id] == @user.id %>
  <div class="enter-bx">
  	<h1>Edit User</h1>
	<%= render 'form' %>
  </div>
  <div class="delete"><%= link_to 'Delete Account', @user, method: :delete, data: {confirm: "Are you sure?"} %></div>
<% else %>
	<%= flash[:alert] = "You must be logged in" %><br>
	<%= link_to 'Back', root_path %>
<% end %>
</body>

app/views/users/index.html.erb
<body class="bg-other">
  <div class="user-wrapper">
    <% @users.each do |user| %>
    <div class="user-list-wrapper">
	  <div class="user-bx">
	  	<h5><%=link_to user.username, user_path(user.id)%></h5>
	  	<%= image_tag user.avatar.url(:thumb) %>
	  </div>
    </div>
    <% end %>
</div>
</body>

app/views/users/new.html.erb
<body class="bg-home">
<div class="container">
	<div class="welcome-wrapper">
		<div class="title"><em>blabber.</em></div>
		<div class="enter-bx">
		<h1>Sign up</h1>
		<%= render 'form' %>
	</div>
</div>
</body>

app/views/users/search.html.erb
<% users.each do |user| %>
  <%= link_to (user.username, user_path(user)) %>
  <p>Username: <%= user.username %></p>
<% end %>

app/views/users/show.html.erb
<body class="bg-other">
<div class="feed-wrapper">
  <h3><%= @user.username %>'s blabs:</h3>
  <div class="avatar-wrapper">
    <div class="avatar"><%= image_tag @user.avatar.url(:medium) %></div>
  </div>
    <% @posts.reverse_each do |post| %>
    <div class="post-wrapper">
      <div class="post">
        <%= post.body %>
      </div>
      <% if session[:user_id] == post.user_id %>
        <div class="edit_delete">
          <%= link_to 'Edit Post', edit_post_path(post.id) %><br>
          <%= link_to 'Delete Post', post_path(post.id), method: :delete, data: {confirm: 'Are you sure?'} %>
        </div>
      <% end %>
      <div class="comments-form">
        <% if session[:user_id] %>
          <h5>Leave a comment:</h5>
          <%= form_for [post, Comment.new] do |f| %>
            <%= f.text_area :body, :id => "comment-bx" %>
            <%= f.submit %>
          <% end %>
        <% else %>
        <p>Please <%=link_to 'Sign In', sign_in_path%> to write a comment.</p>
        <% end %>
      </div>

      <div class="comments-list">
        <% post.comments.each do |comment| %>
          <h5><%= comment.user.username %>:</h5>
          <p><%= comment.body %></p>
          <% if session[:user_id] == @user %>
            <%= link_to 'Delete Comment', comment_path(post.id), method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        <% end %>
      </div>
    </div>
    <% end %>
</div>
</body>